version: "3.9"

services:
  db:
    container_name: db-app
    env_file: .env
    build:
      context: requirements/mariadb
      dockerfile: Dockerfile
      args:
        USERNAME: ${USERNAME}
        USER_PASSWORD: ${USER_PASSWORD}
        MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
        DB_NAME: ${DB_NAME}
    ports:
      - 3307:3307
    # configure the below healthcheck accordingly to what you need
    # healthcheck:
      # test: ["CMD", "curl", "-f", "http://localhost"]
      # interval: 1m30s
      # timeout: 10s
      # retries: 3
      # start_period: 40s
    # restart: always
    networks:
      - inception
    # command:
      # tail -F anything
# 2 line above to del

  wordpress:
    build:
      context: requirements/wordpress
      dockerfile: Dockerfile
      args:
        USERNAME: ${USERNAME}
        USER_PASSWORD: ${USER_PASSWORD}
    networks:
      - inception

#  nginx:
#    build:
#      context: requirements/nginx
#      dockerfile: Dockerfile
#    networks:
#      - inception

volumes:
  wordpress-db:

  wordpress-files:

networks: 
  inception:

# each env variable you need need to be specified in each service