version: "3.9"

services:
  database:
    container_name: mariadb
    env_file: .env
    build:
      context: requirements/mariadb
      dockerfile: Dockerfile
      args:
        USER_NAME: ${USER_NAME}
        USER_PASSWORD: ${USER_PASSWORD}
        MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
        DB_NAME: ${DB_NAME}
    restart: on-failure
    volumes:
      - wordpress-database:/var/lib/mysql
    networks:
      - inception

  server:
    container_name: nginx
    depends_on:
      - site
    build:
      context: requirements/nginx
      dockerfile: Dockerfile
    ports:
      - 443:443
    restart: on-failure
    volumes:
      - nginx-logs:/home/sylducam/data/log/nginx
      - wordpress-files:/var/www/html/wordpress
    networks:
      - inception

  site:
    container_name: wordpress
    depends_on:
      - database
    env_file: .env
    build:
      context: requirements/wordpress
      dockerfile: Dockerfile
      args:
        USER_NAME: ${USER_NAME}
        USER_PASSWORD: ${USER_PASSWORD}
        DB_NAME: ${DB_NAME}
        WP_USER_NAME: ${WP_USER_NAME}
        WP_USER_PASSWORD: ${WP_USER_PASSWORD}
        WP_USER_EMAIL: ${WP_USER_EMAIL}
    restart: on-failure
    volumes:
      - wordpress-files:/var/www/html/wordpress
    networks:
      - inception
      
volumes:
  wordpress-database:
    driver_opts:
      type: none
      o: bind
      device: "/home/sylducam/data/wordpress_database"

  wordpress-files:
    driver_opts:
      type: none
      o: bind
      device: "/home/sylducam/data/wordpress_files"

  nginx-logs:
    driver_opts:
      type: none
      o: bind
      device: "/home/sylducam/data/log/nginx"

networks:
  inception: {}