version: "3.9"

services:
  db:
    container_name: mariadb
    env_file: .env
    build:
      context: requirements/mariadb
      dockerfile: Dockerfile
      args:
        USER_NAME: ${USER_NAME}
        USER_PASSWORD: ${USER_PASSWORD}
        MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
        DB_NAME: ${DB_NAME}
    # volumes:
      # wordpress-db:
    ports:
      - 3307:3307
    # configure the below healthcheck accordingly to what you need
    # healthcheck:
      # test: ["CMD", "curl", "-f", "http://localhost"]
      # interval: 1m30s
      # timeout: 10s
      # retries: 3
      # start_period: 40s
    # restart: always
    # networks:                                                       # ++
      # - inception                                                   # ++
    # command:
      # tail -F anything
# 2 line above to del

  wordpress:
    container_name: wordpress
    env_file: .env
    build:
      context: requirements/wordpress
      dockerfile: Dockerfile
      args:
        USER_NAME: ${USER_NAME}
        USER_PASSWORD: ${USER_PASSWORD}
    # networks:
      # - inception

  nginx:
    container_name: nginx
    env_file: .env # needed ?
    build:
      context: requirements/nginx
      dockerfile: Dockerfile
      
# networks:
#   - inception

# volumes:
  # wordpress-db:

  # wordpress-files:

# networks: 
#   inception:

# each env variable you need need to be specified in each service