version: "3.9"

services:
  database:
    container_name: mariadb
    env_file: .env
    build:
      context: requirements/mariadb
      dockerfile: Dockerfile
      args:
        USER_NAME: ${USER_NAME}
        USER_PASSWORD: ${USER_PASSWORD}
        MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
        DB_NAME: ${DB_NAME}
    volumes:
      - wordpress-files:/home/sylducam/data/wordpress_database
    # configure the below healthcheck accordingly to what you need
    # healthcheck:
      # test: ["CMD", "curl", "-f", "http://localhost"]
      # interval: 1m30s
      # timeout: 10s
      # retries: 3
      # start_period: 40s
    # restart: always
    networks:                                                       # ++
      - inception                                                   # ++
    # command:
      # tail -F anything
# 2 line above to del

  server:
    container_name: nginx
    depends_on:
      - site
    env_file: .env # needed ?
    build:
      context: requirements/nginx
      dockerfile: Dockerfile
    ports:
      - 443:443
    volumes:
      - nginx-logs:/home/sylducam/data/log/nginx
      - wordpress-files:/var/www/html/wordpress
    networks:
      - inception

  site:
    container_name: wordpress
    depends_on:
      - database
    env_file: .env
    build:
      context: requirements/wordpress
      dockerfile: Dockerfile
      args:
        USER_NAME: ${USER_NAME}
        USER_PASSWORD: ${USER_PASSWORD}
        DB_NAME: ${DB_NAME}
    volumes:
      - wordpress-files:/var/www/html/wordpress
    networks:
      - inception
      
volumes:
  wordpress-database:
    driver_opts:
      type: none
      o: bind
      device: "/home/sylducam/data/wordpress_database"

  wordpress-files:
    driver_opts:
      type: none
      o: bind
      device: "/home/sylducam/data/wordpress_files"

  nginx-logs:
    driver_opts:
      type: none
      o: bind
      device: "/home/sylducam/data/log/nginx"

networks:
  inception: {}


# each env variable you need need to be specified in each service