version: "3.9"

services:
  db:
    build:
      context: requirements/mariadb
      dockerfile: Dockerfile
    ports:
      - 3307:3307
    networks:
      - inception

#  wordpress:
#    build:
#      context: requirements/wordpress
#      dockerfile: Dockerfile
#    networks:
#      - inception

#  nginx:
#    build:
#      context: requirements/nginx
#      dockerfile: Dockerfile
#    networks:
#      - inception

volumes:
  wordpress-db:

  wordpress-files:

networks: 
  inception: