version: "3.9"

services:
  db:
    container_name: db-app
    build:
      context: requirements/mariadb
      dockerfile: Dockerfile
    env_file: .env
    environment:
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - 3307:3307
    # configure the below healthcheck accordingly to what you need
    # healthcheck:
      # test: ["CMD", "curl", "-f", "http://localhost"]
      # interval: 1m30s
      # timeout: 10s
      # retries: 3
      # start_period: 40s
    # restart: always
    networks:
      - inception
    # command:
      # tail -F anything
# 2 line above to del

#  wordpress:
#    build:
#      context: requirements/wordpress
#      dockerfile: Dockerfile
#    networks:
#      - inception

#  nginx:
#    build:
#      context: requirements/nginx
#      dockerfile: Dockerfile
#    networks:
#      - inception

volumes:
  wordpress-db:

  wordpress-files:

networks: 
  inception:

# each env variable you need need to be specified in each service