docker run --detach --name some-mariadb --env MARIADB_USER=sylducam --env\
MARIADB_PASSWORD=blabla --env MARIADB_ROOT_PASSWORD=blabla  mariadb:latest
# should I use "latest" >> see message from tglory on compatibility OS/pkg (Debian 10/11)
