CREATE DATABASE IF NOT EXISTS DB_NAME;
CREATE USER 'USER_NAME' IDENTIFIED BY 'USER_PASSWORD';
GRANT ALL ON DB_NAME.* TO 'USER_NAME'@'%';
FLUSH PRIVILEGES;
ALTER USER 'root'@'localhost' IDENTIFIED BY 'MYSQL_ROOT_PASSWORD';
